#if (useDspGenerator)
//  This file is generated by a tool from the file ColorPaletteOverride.zip -- YOU SHOULD NOT EDIT IT manually.
#endif
using Uno.Extensions.Markup;

namespace Tracker.Frontend.Uno.Styles;

public sealed partial class ColorPaletteOverride : ResourceDictionary
{
    public ColorPaletteOverride()
    {
        this.Build(r => r.Add(Theme.Colors.Primary.Default, "#5946D2", "#C7BFFF")
            .Add(Theme.Colors.Primary.Inverse, "#C8BFFF", "#2A009F")
            .Add(Theme.Colors.Primary.Container, "#E5DEFF", "#4129BA")
            .Add(Theme.Colors.OnPrimary.Default, "#FFFFFF", "#2A009F")
            .Add(Theme.Colors.OnPrimary.Container, "#170065", "#E4DFFF")
            .Add(Theme.Colors.Secondary.Default, "#6B4EA2", "#CDC2DC")
            .Add(Theme.Colors.Secondary.Container, "#EBDDFF", "#433C52")
            .Add(Theme.Colors.OnSecondary.Default, "#FFFFFF", "#332D41")
            .Add(Theme.Colors.OnSecondary.Container, "#220555", "#EDDFFF")
            .Add(Theme.Colors.Tertiary.Default, "#0061A4", "#9FCAFF")
            .Add(Theme.Colors.Tertiary.Container, "#CFE4FF", "#00497D")
            .Add(Theme.Colors.OnTertiary.Default, "#FFFFFF", "#003258")
            .Add(Theme.Colors.OnTertiary.Container, "#001D36", "#D1E4FF")
            .Add(Theme.Colors.Error.Default, "#B3261E", "#FFB4AB")
            .Add(Theme.Colors.Error.Container, "#F9DEDC", "#93000A")
            .Add(Theme.Colors.OnError.Default, "#FFFFFF", "#690005")
            .Add(Theme.Colors.OnError.Container, "#410E0B", "#FFDAD6")
            .Add(Theme.Colors.Background.Default, "#FCFBFF", "#1C1B1F")
            .Add(Theme.Colors.OnBackground.Default, "#1C1B1F", "#E5E1E6")
            .Add(Theme.Colors.Surface.Default, "#FFFFFF", "#302D37")
            .Add(Theme.Colors.Surface.Variant, "#F2EFF5", "#47464F")
            .Add(Theme.Colors.Surface.Inverse, "#313033", "#E6E1E5")
            .Add(Theme.Colors.Surface.Tint, "#5946D2", "#C7BFFF")
            .Add(Theme.Colors.OnSurface.Default, "#1C1B1F", "#E6E1E5")
            .Add(Theme.Colors.OnSurface.Variant, "#8B8494", "#C9C5D0")
            .Add(Theme.Colors.OnSurface.Inverse, "#F4EFF4", "#1C1B1F")
            .Add(Theme.Colors.Outline.Default, "#79747E", "#928F99")
            .Add(Theme.Colors.Outline.Variant, "#C9C5D0", "#57545D"));
    }
}
